services:
  - type: web
    name: n8n-philips-smart-system
    env: docker
    plan: free
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_PORT
        value: 10000
      - key: WEBHOOK_URL
        value: https://n8n-philips-smart-system.onrender.com/
      - key: N8N_HOST
        value: n8n-philips-smart-system.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: N8N_METRICS
        value: true
